### ISSUE TITLE
Missing File for vocabuary conversion

### ISSUE THREAD

**Issue by LeiGong0125Carrot** [pat-jj/GraphCare#18]
Hello, thank you for sharing this amazing work!
When I directly run the code of data_prepare.py, there are also occurs such errors that indicate it can not download the vocabulary conversion file. Could you please help me with it?
Traceback (most recent call last):
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/medcode/cross_map.py", line 44, in __init__
    df = download_and_read_csv(local_filename, refresh_cache)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/medcode/utils.py", line 33, in download_and_read_csv
    urlretrieve(online_filepath, local_filepath)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sfs/weka/scratch/nkw3mr/sdoh_clinical_outcome_prediction/clinical-outcome-prediction/GraphCare/data_prepare.py", line 528, in <module>
    main()
  File "/sfs/weka/scratch/nkw3mr/sdoh_clinical_outcome_prediction/clinical-outcome-prediction/GraphCare/data_prepare.py", line 523, in main
    run(dataset, task)
  File "/sfs/weka/scratch/nkw3mr/sdoh_clinical_outcome_prediction/clinical-outcome-prediction/GraphCare/data_prepare.py", line 489, in run
    sample_dataset = load_dataset(load_processed_dataset, dataset=dataset, task=task)
  File "/sfs/weka/scratch/nkw3mr/sdoh_clinical_outcome_prediction/clinical-outcome-prediction/GraphCare/data_prepare.py", line 66, in load_dataset
    ds = MIMIC4Dataset(
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/datasets/base_dataset.py", line 92, in __init__
    self.code_mapping_tools = self._load_code_mapping_tools()
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/datasets/base_dataset.py", line 143, in _load_code_mapping_tools
    code_mapping_tools[f"{s_vocab}_{t_vocab}"] = CrossMap(s_vocab, t_vocab)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/medcode/cross_map.py", line 47, in __init__
    df = download_and_read_csv(local_filename, refresh_cache)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/site-packages/pyhealth/medcode/utils.py", line 33, in download_and_read_csv
    urlretrieve(online_filepath, local_filepath)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/nkw3mr/.conda/envs/graphcare/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by pat-jj** [comment]
Could you show your code of `load_dataset`?

**Comment by LeiGong0125Carrot** [comment]
> Could you show your code of `load_dataset`?

I am sorry for interrupting, I figured that out.

**Comment by pat-jj** [comment]
Glad to know that!
